### ISSUE TITLE
Current known issues

### ISSUE THREAD

**Issue by TheWinABagel** [TheWinABagel/Zenith#1]
- [ ] Enchantment module
    - [ ] Enchantment library
        - [ ] Fix enchantment library saving level 0 enchants as nbt
    - [ ] Random mod support
        - [ ] Knowledge of the ages
            - [ ] make it work with droplight
            - [ ] make it incompatible with soul siphon and soul devourer? with config
        - [ ] Goblin trader support, make max level of tools match max enchantment level
 
- [ ] Spawner Module
    - [ ] Mob Spawners
        - [ ] Make them not drop xp
        - [x] Fix rendering when spawn egg changed

- [ ] Potion Module
    - [ ] rei rendering of charms with recipes is weird
    - [ ] todo

- [x] Village module
    - [x] none known

- [x] Garden Module
    - [x] none known

- [ ] Adventure Module
    - [ ] Implement

**Comment by kirishino** [comment]
cant mine stone with any pickaxe its like as if im mining with hand it doesnt drop aswell
