### ISSUE TITLE
All stones hard to break

### ISSUE THREAD

**Issue by slammaja** [TheWinABagel/Zenith#10]
Hi,

after updating to 5.5 all stone blocks (vanilla and modded ones) became hard to break like having too high mining level and they don't drop themselves (same effect as if you mine obsidian with iron pickaxe for example).

**Comment by TheWinABagel** [comment]
Could you share your mod list? I think it might be a mod interaction issue

**Comment by slammaja** [comment]
I'll send list as soon as I get to PC. BTW on version 4.2 of Zenith everything works fine - anvil enchantments, tomes.
