### ISSUE TITLE
Using Zenith Attributes 0.1.4 with Zenith 1.0.2 crashes

### ISSUE THREAD

**Issue by Thelegendking** [TheWinABagel/Zenith#104]
Using Zenith Attributes 0.1.4 with Zenith 1.0.2 crashes but switching Zenith Attributes 0.1.4 with 0.1.3 seems to be okay with latest Zenith mod.

**Comment by TheWinABagel** [comment]
Log?

**Comment by serioos** [comment]
I have this problem as well.

(zenith-1.0.1-1.20.1.jar and zenith_attributes-0.1.3.jar work fine)

(zenith 1.0.3-1.20.1 and zenith_attributes-0.1.4.jar cause crash at the game run)


I suspect it is a conflict with another mod that has been developed in the latest version of the Zenith.  When I downgrade Zenith and the Zenith Attributes, the game load up fine, but when I upgrade them to the latest version, the game crashes at the start. Here's my log:

https://pastebin.com/cCUSUPF3

Could it be a conflict with ShowYourSkin or Time Control perhaps?

**Comment by Thelegendking** [comment]
I don't have neither of those mods so definitely problem is not them, and I'll put the log when I get home sorry I forgot.

**Comment by Thelegendking** [comment]
Issue is fixed now with the latest versions of Zenith & Zenith Att. mods, thanks
