### ISSUE TITLE
I break the blocks, but nothing falls out 1.20.1

### ISSUE THREAD

**Issue by xpkq** [TheWinABagel/Zenith#105]
Hello!

I put Zenith and Zenith's Attributes mods on my build. Minecraft and the world loaded as usual, but when you try to break any block, after breaking it, nothing falls out. No matter what tool I use, nothing falls out of the destroyed blocks.

**Comment by TheWinABagel** [comment]
Could I have some more info, like modlist? 
Can you recreate with just zenith attributes or do you need zenith as well?

**Comment by Partonetrain** [comment]
@TheWinABagel this was an issue with portinglib. See https://github.com/TheWinABagel/ZenithAttributes/issues/3

**Comment by TheWinABagel** [comment]
Fixed with latest porting lib, update to 1.1.0
