### ISSUE TITLE
Registry entry mismatch with server (same versions)

### ISSUE THREAD

**Issue by Sooperfish** [TheWinABagel/Zenith#107]
Hi, when I try to join my server with 1.0.4, I get a registry entry mismatch screen. I've confirmed that the library, attribute mod and the main mod are the same version on client and server.
![Screenshot 2024-02-03 021732](https://github.com/TheWinABagel/Zenith/assets/5457984/cfc3d164-1beb-4012-a17d-5fb998c3d7e8)

https://mclo.gs/Suub7a6

**Comment by TheWinABagel** [comment]
The server has the spawner module enabled and you have it disabled on your client.
