### ISSUE TITLE
Enchanting module broken?

### ISSUE THREAD

**Issue by Utelys** [TheWinABagel/Zenith#111]
So i am currently on zenith 1.0.4 for 1.20.1. I am using the Better MC Fabric (BMC2) and i installed Zenith on it. I noticed that the 3 bars for showing eterna, quanta and arcana are not present in the enchanting table but are showing in topright corner when crosshair is on the enchanting table. 

When i upgraded some of my bookshelves to hellshelves the enchanting levels in the enchanting table went down to 16. It seems that its not registering the modded shelves as enchanting powered blocks. I am guessing the same is happening for candles as i got arcana high enough for always 2 enchantments but are getting single enchantments on items at lvl 30. 

Is there something i am missing that is causing this problem. Seems that the other stuff is working fine as bosses are spawning. Haven't gotten too far into the game so unsure about all the modules but items have different affixes and mobs are dropping gems.

**Comment by muon-rw** [comment]
Remove the EasyMagic mod, then break and replace your Enchanting Table

**Comment by Utelys** [comment]
> Remove the EasyMagic mod, then break and replace your Enchanting Table

Im guessing EasyAnvils mod will also collide with some of the mechanics from Zenith?

**Comment by Utelys** [comment]
> Remove the EasyMagic mod, then break and replace your Enchanting Table

And thank you btw! It worked :)

**Comment by muon-rw** [comment]
> > Remove the EasyMagic mod, then break and replace your Enchanting Table
> 
> Im guessing EasyAnvils mod will also collide with some of the mechanics from Zenith?

As far as I know, Easy Anvils simply doesn’t work if Zenith is installed (Except for probably the nametag features)
