### ISSUE TITLE
Jei issues (recipes not visibles, items not listed)

### ISSUE THREAD

**Issue by Heargo** [TheWinABagel/Zenith#117]
Fabric 1.20.1
The charms and gems are not visible in JEI and the charms recipes are not detected

You can see here that only the cracked basalt is visible in jei. And only 1 Charm as well.
![Capture d'écran 2024-03-10 100833](https://github.com/TheWinABagel/Zenith/assets/60543512/1e07f43b-cec6-405e-8403-a52549f45f58)

And here when I tried to show the recipe from a charm in my inventory I get this :
![Capture d'écran 2024-03-10 101225](https://github.com/TheWinABagel/Zenith/assets/60543512/a60ab606-cf1c-4fb1-a9b2-ab865d761bd0)

As for minimal reproducible examples I couldn't do better than the following list of mods as when I only used zenith and it's dependencies I had [an error related to zenith attributes](https://github.com/TheWinABagel/ZenithAttributes/issues/9) that didn't occurred when using it with other mod (might be linked but I'm not sure).

Here is the list of mod I'm using in context of the logs when starting the game :
[latest.log](https://github.com/TheWinABagel/Zenith/files/14549666/latest.log)

**Comment by TheWinABagel** [comment]
JEI is not supported, use REI or EMI.
