### ISSUE TITLE
Zenith 1.1.0-1.20.1 requires unreleased version of ZenithAttributes (0.2.0.1)

### ISSUE THREAD

**Issue by maikotui** [TheWinABagel/Zenith#120]
Latest Zenith is requiring 0.2.0.1 or later of Zenith Attributes. Zenith Attributes version 0.2.0.1 has not been released (and from what I can tell, the source hasn't changed). I'm guessing this is due to waiting for the PortingLib dependency upgrade, but I wanted to make sure this was an intentional change to Zenith's dependencies.

**Comment by TheWinABagel** [comment]
Crap
Will release a hotfixed version rq

**Comment by maikotui** [comment]
1 minute response time, what a legend

**Comment by TheWinABagel** [comment]
Discord webhooks woooo

**Comment by TheWinABagel** [comment]
It's uploading, it might take a few minutes to accept (modrinth might accept first)
