### ISSUE TITLE
Zenith 1.1.1 spamming "Failed to execute LootRule" errors in server console

### ISSUE THREAD

**Issue by temyy** [TheWinABagel/Zenith#121]
Log attached, error gets sent at seemingly random intervals, not sure if it actually does anything fatal. Ctrl+F also highlighted other various errors during startup, not sure if theyre related.
[latest.log](https://github.com/TheWinABagel/Zenith/files/14577338/latest.log)

**Comment by SiVy1** [comment]
I think that error gets sent whenever agressive mob attempts to spawn and prevent them from spawning

Edit: Also have same error

**Comment by TheWinABagel** [comment]
Could you post the log again? It seems to be unreachable

**Comment by SiVy1** [comment]
[latest.log](https://github.com/TheWinABagel/Zenith/files/14578816/latest.log)
I downloaded it earlier by some miracle

**Comment by TheWinABagel** [comment]
Hmm... still not working, try using [mclogs](https://mclo.gs/) maybe?

**Comment by SiVy1** [comment]
there you go https://mclo.gs/3Dkv3sI

edit: paste wrong logs xD

**Comment by TheWinABagel** [comment]
Looks like I updated a dependency and it removed something... I'll get a fix out for it soon

**Comment by TheWinABagel** [comment]
That being said, the 
`(Zenith : Adventure) Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity zenith:uncommon for category shovelRequired: 3; Provided: 2`
thing is not an issue

**Comment by TheWinABagel** [comment]
`(Zenith : Adventure) Failed to execute LootRule minecraft:iron_pickaxe/zenith:uncommon/STAT/0.45!` is also not an important issue as far as I know

**Comment by TheWinABagel** [comment]
Fixed in 1.1.2
