### ISSUE TITLE
crash on attempted mob spawn(?), possible incompatibility with amethyst core/imbued gear

### ISSUE THREAD

**Issue by temyy** [TheWinABagel/Zenith#124]
crash log https://mclo.gs/MCjJ4pi
latest log https://mclo.gs/xBbJtnO

crash log seems to point to amethyst core and the mods associated with it along with zenith and porting lib, if needed i can also report this to ACs side

**Comment by TheWinABagel** [comment]
Try updating amethyst core and the mods that depend on it, it looks like there's a mismatch of some sort. Nothing to do with zenith, though

**Comment by temyy** [comment]
this is after the updates, i guess the reworks broke something. ill post this there

**Comment by TheWinABagel** [comment]
Possible, I looked at the code and that method name changed within the last few months
