### ISSUE TITLE
(Zenith 1.1.2-1.20.1) Breaking spawners crashes server

### ISSUE THREAD

**Issue by maikotui** [TheWinABagel/Zenith#127]
When a player breaks any natural spawner, the server crashes. We are using a custom modpack, so it could just be a conflict of some sort. I'm trying to figure out how to repro it with the minimum amount of mods. It could have something to do with me having the ~~adventure~~ spawner* module turned off. I'll update if I can get a better repro.

[crash-2024-03-14_05.46.31-server.txt](https://github.com/TheWinABagel/Zenith/files/14608934/crash-2024-03-14_05.46.31-server.txt)

**Comment by maikotui** [comment]
OK found the minimum repro. I attached my zenith config. Just load an empty world with this config (spawner module disabled) and the server crashes when you break a spawner.

[crash-2024-03-14_17.50.53-server.txt](https://github.com/TheWinABagel/Zenith/files/14608955/crash-2024-03-14_17.50.53-server.txt)

[zenith.cfg.txt](https://github.com/TheWinABagel/Zenith/files/14608958/zenith.cfg.txt)

**Comment by TheWinABagel** [comment]
I figured this one out earlier today actually, will get a release out fixing it soon (today or tomorrow, currently away from dev machine)

**Comment by maikotui** [comment]
Confirmed fixed on Zenith version 1.1.5
