### ISSUE TITLE
Sockets disappear and ZENITH_REMOVE_MARKER shows up

### ISSUE THREAD

**Issue by kiishiio** [TheWinABagel/Zenith#128]
problem:
when i put a gem inside a socket the sockets just disappear and wont let me see the gems i put into them anymore

before:
![image](https://github.com/TheWinABagel/Zenith/assets/98748787/06a216c1-b76d-4c56-a96a-eaaa0b29d11e)
(and for some reason the text is bugged, probably bc of legendary tooltips but i dunno)

after i put gem in:
![image](https://github.com/TheWinABagel/Zenith/assets/98748787/9453bf3d-c424-44c7-a493-a1e509adf2e8)

**Comment by muon-rw** [comment]
Does this issue persist if you remove Tierify?

**Comment by kiishiio** [comment]
nope
also i use TieredZ if that does change anything. (ik code is probably identical)
would there be any way to compat this?

**Comment by maikotui** [comment]
+1 for repro on this with TieredZ + Zenith Adventure Module

**Comment by TheWinABagel** [comment]
TieredZ's mixin breaks it, not much can be done by me. The mixin doesn't seem to be written with compat in mind.
Remove TieredZ, or deal with it, sorry. :(
