### ISSUE TITLE
Bosses still not spawning with only Zenith mods, and adjusted spawn rate 1. 20.1

### ISSUE THREAD

**Issue by ShadowXxEclipse** [TheWinABagel/Zenith#129]
Making a pack, zenith bosses were not randomly spawning.

I tested in singleplayer, and bosses still do not spawn, I am not sure why, but  I used only the main dependencies it needed for testing. 

I have seen this as an issue before, but testing proves that it is broken or something is incredibly wrong on my side.

**Comment by seefourr** [comment]
+1

**Comment by TheWinABagel** [comment]
Was an arch issue, I implemented a temp fix in 1.1.6 (will PR some stuff to arch to fix it)
