### ISSUE TITLE
Question: Compatibility With Other Mods' Enchantments

### ISSUE THREAD

**Issue by maikotui** [TheWinABagel/Zenith#130]
I'm running a lot of the RPG Series mods which feature some custom enchantments such as Spell Volatility, Sunfire, etc. I'm just now noticing that the enchantment library is eating these enchantments and they don't show up in the list. Is this expected? I've seen the enchantment library work in other mad packs with enchants from MC Dungeons Armor, but I'm not seeing the RPG series enchants work.

**Comment by maikotui** [comment]
Investigating this, looks like the enchantment is registered in the data for the library, but it doesn't show up in the UI. Investigating code right now.

![image](https://github.com/TheWinABagel/Zenith/assets/32694968/05da0c92-24fd-43bd-9228-4579fe33f69f)
![image](https://github.com/TheWinABagel/Zenith/assets/32694968/8d194fc6-677b-4b02-a696-b86bd09d79a0)

**Comment by maikotui** [comment]
Could be an issue on the Spell Power mod side as well. For some reason, I see the "spell_power:magic_protection" enchantment in the UI but not the "spell_power:sunfire" enchant. Both exist in the enchantments.cfg and have the same configuration.

**Comment by maikotui** [comment]
Sorry for the spam, but I figured something out. If I place an item that can take the Sunfire enchantment in the filter slot, it will then show up. Otherwise, it'll be missing. So it's got something to do with net.spell_power.api.enchantment.EnchantmentRestriction. Maybe we're still applying the enchantment restrictions even if the filter is null?

**Comment by TheWinABagel** [comment]
Ah, nice investigating! I'll upload a version with the fix shortly

**Comment by TheWinABagel** [comment]
Should be fixed with 1.1.5
