### ISSUE TITLE
How to spawn an item with specific rarity

### ISSUE THREAD

**Issue by danieldraper** [TheWinABagel/Zenith#136]
Another mod caused an item to be destroyed, I was unable to spawn a new one of the same rarity. I assume I could do something like:

`/give PLAYER_NAME simplyswords:molten_edge{affix_data: {rarity: "mythic"}} 1`

Is this possible from the console?

**Comment by seefourr** [comment]
"/zenith ..." command should have what you are looking for I believe

**Comment by TheWinABagel** [comment]
`/zenith lootify rarityGoesHere`, there is currently no way to edit specific affixes though
