### ISSUE TITLE
Enchanting library hides enchantment from Spellblades unless filter item from the mod is used

### ISSUE THREAD

**Issue by atealein** [TheWinABagel/Zenith#137]
Hey,

I noticed this behavior in Prominence - Void's Invasion (Fabric) modpack. At first I even thought that the enchanting library was voiding the enchantments because they weren't showing in it, but another player told me if I use spellblade or orb in the "Filter Item" slot, then they appear and that's correct. 

So opening the issue because it is inconsistent behavior for the enchantment books from this mod and any other mod, really.

Expected behavior: If no filter item is used you should be able to see all the enchantments contained in the library. (Additional point is - if you use a book as filter item, you should also be able to see all enchantments as they are all on books, but actually almost no show up?)

Modpack version 2.7.7hf, it uses Zenith v1.0.2 - 1.20.1 and Spellblades and Such v1.7.2.1

**Comment by TheWinABagel** [comment]
This has been fixed for a couple months, but prominence cant update zenith currently for various reasons.
