### ISSUE TITLE
Incompatibility: Easy Magic & Easy Anvils

### ISSUE THREAD

**Issue by muhammedesadcomert** [TheWinABagel/Zenith#138]
There are some incompatibility issues (like cannot increase the level progression with upgrading bookshelves) between these mods as you know. Can you add incompatibility information to the Modrinth page or pin the issue? Because people don't have to spend hours trying to find the problem.

**Comment by seefourr** [comment]
I would think this would be assumed; both easy magic and zenith modify the enchanting system to some extent and generally mods don't like other mods interfering in their function. Also zenith lets you keep lapis in the enchanting table anyway.

**Comment by TheWinABagel** [comment]
Yep, they are incompatible by design
