### ISSUE TITLE
Silk touch is breaking the mob spawner

### ISSUE THREAD

**Issue by ihugow** [TheWinABagel/Zenith#139]
When trying to break a mob spawner with a pickaxe enchanted with silk touch, the spawner breaks and does not drop its item...

**Comment by singulantlive** [comment]
I am having this issue as well. I have set the config to 0 and -1 on different occasions and cannot get it to work. Ive tried server setting and single player, spawner always breaks.

**Comment by TheWinABagel** [comment]
Fixed with 1.1.10
