### ISSUE TITLE
Disabling 

### ISSUE THREAD

**Issue by Paxx3** [TheWinABagel/Zenith#144]
Is there a way to disable some enchants or whatever it is called like step hight, giving extra health, swim speed, mining speed etc. on items or gems? I cannot understand the files on config.

**Comment by muon-rw** [comment]
Those are affixes, you can edit, remove, or add new affixes or gems with a datapack. 
See: 
https://github.com/TheWinABagel/Zenith/tree/1.20/src/main/resources/data/zenith/affixes
https://github.com/TheWinABagel/Zenith/tree/1.20/src/main/resources/data/zenith/gems

**Comment by TheWinABagel** [comment]
Make a datapack for it, as muon said

**Comment by TheWinABagel** [comment]
Replacing the affix you want with a json file with just 
```json
{
 "fabric:load_conditions": [
    {
      "condition": "fabric:not",
      "value": {
        "condition": "fabric:all_mods_loaded",
        "values": [
          "zenith"
        ]
      }
    }
  ]
}
  ```
  should work
  
  fabric doesnt have a false condition annoyingly lol
