### ISSUE TITLE
Hard dependency on fabric api version

### ISSUE THREAD

**Issue by solonovamax** [TheWinABagel/Zenith#145]
When attempting to launch with the latest fabric api version, the mod will not launch and will log
```
Mod 'Zenith' (zenith) 1.1.7-1.20.1 requires version 0.92.0+1.20.1 of mod 'Fabric API' (fabric-api), but only the wrong version is present: 0.92.1+1.20.1!
```

This is because of [this](https://github.com/TheWinABagel/Zenith/blob/1.20/src/main/resources/fabric.mod.json#L71) line, where you don't specify `"fabric": ">=${fapi_version}",`, but rather `"fabric": "${fapi_version}",`.
Thus, it is not compatible with all future versions of fabric api, requiring constant updates.

**Comment by TheWinABagel** [comment]
Crap.
Fixed in 1.1.8
