### ISSUE TITLE
Not saving Wizard RPG mod enchantments like Spell haste or Spell volatility

### ISSUE THREAD

**Issue by carloscopy** [TheWinABagel/Zenith#148]
https://www.curseforge.com/minecraft/mc-mods/spell-power

Doesn't save spell power attributes ecnhantments

**Comment by muon-rw** [comment]
Can you be a bit more specific, what do you mean by "doesn't save"? Which mod versions are you using?

**Comment by TheWinABagel** [comment]
Sounds like #137, bug is fixed in newer versions but prominence is still on an older version. Not much I can do.
