### ISSUE TITLE
Disable durability damage attributes

### ISSUE THREAD

**Issue by duarm** [TheWinABagel/Zenith#152]
Thanks for making zenith!

I'm playing with "No durability", which disables durability, it would be nice if we could blacklist the "This item ignores % durability" effect (pic below), in order to save a little bit of space.

![image](https://github.com/TheWinABagel/Zenith/assets/26150581/27c3e0de-b2d2-44d4-a5d7-c1b44df4506f)

**Comment by muon-rw** [comment]
I was going to comment "you can disable it with a datapack" but the file contents specifically say not to: 
```
{
	"type": "zenith:durable",
	"_comment": "The durable affix is an internal-only marker affix. Do not edit or remove this file. If you are looking for config options related to the durability buff, see adventure.cfg"
}
```

However, adventure.cfg seems to contain nothing related to durability affixes. 

If this same inconsistency is present in Apotheosis, it should probably be reported there instead.

**Comment by TheWinABagel** [comment]
Modify these files via datapack: https://github.com/TheWinABagel/Zenith/tree/1.20/src/main/resources/data/zenith/rarities
