### ISSUE TITLE
Zenith bookshelves don't work with vanilla enhancement table

### ISSUE THREAD

**Issue by Redhawk18** [TheWinABagel/Zenith#17]
enhancement table doesn't get levels from modded bookshelves.

Zenith bookshelves
![huge_2023-04-25_17 16 04](https://user-images.githubusercontent.com/77415970/234408583-21ef97dd-51d8-402a-9ffb-c544ea517972.png)

vanilla bookshelves
![huge_2023-04-25_17 16 35](https://user-images.githubusercontent.com/77415970/234408675-4cf682f0-3f29-4a52-af48-e3e2299e3169.png)

**Comment by TheWinABagel** [comment]
It looks like theres a mod overriding the default enchanting table screen, most likely "Easy magic"
Uninstalling and then breaking/replacing the enchantment table will fix the issue
