### ISSUE TITLE
Can't infuse dragon's breath

### ISSUE THREAD

**Issue by Cocomere** [TheWinABagel/Zenith#176]
I'm stuck at the deepshelf stage because it keeps saying that the enchantment criteria isn't met to infuse dragon's breath. I have a full set of Soultouched & Echoing Deepshelves, but I've tried swapping some of them for other shelves. No dice. It's not my xp either-- I have 104 levels right now.

The shelves say they have a max eterna of 40 and I can't seem to get above that without the dragon's breath. Nothing in the book says that there's other things I need to do, just that I need Soultouched & Echoing bookshelves to get to 80.

I'm playing on fabric 1.20.1 with a lot of mods. I can post a list of them if that helps.

Here's my setup, info from WTHIT, and the table UI showing that I'm not able to do the infusion.

![image](https://github.com/TheWinABagel/Zenith/assets/65450169/c281aaf7-9461-4a8e-80cd-37acdeb2c771)
![image](https://github.com/TheWinABagel/Zenith/assets/65450169/396dab3c-e2b2-4d7b-b253-7f890e114ed2)
![image](https://github.com/TheWinABagel/Zenith/assets/65450169/5f968df3-9aea-4790-b3bc-1c573008d76e)

**Comment by KuschelKaktus88** [comment]
its because u have to much quanta, it requires at least 15 % but no more then 20% quanta

**Comment by Cocomere** [comment]
> its because u have to much quanta, it requires at least 15 % but no more then 20% quanta

Sorry I never replied, but this worked. Thank you!
