### ISSUE TITLE
Zenith 1.1.9 for Minecraft 1.20.1 not dropping spawner when breaking with silk touch

### ISSUE THREAD

**Issue by JasiekGamer** [TheWinABagel/Zenith#177]
I tried to break spawners with silk touch on a diamond and a netherite pickaxe but can't get it to drop the spawner. I tried it on naturally generated minecraft spawners and placed ones.

**Comment by TheWinABagel** [comment]
~~Is the spawner module enabled in the config?~~ Nevermind, something broke

**Comment by TheWinABagel** [comment]
Fixed with 1.1.10
