### ISSUE TITLE
Server Crashes 

### ISSUE THREAD

**Issue by katenip** [TheWinABagel/Zenith#18]
[Server] main/[ERROR] Enchantment zenith:life_mending has min/max power 205/200 at level 4, making this level unobtainable.
Server] main/[ERROR] Enchantment zenith:knowledge has min/max power 235/200 at level 4, making this level unobtainable.
[Server] main/[ERROR] Enchantment zenith:rebounding has min/max power 202/200 at level 6, making this level unobtainable.

**Comment by TheWinABagel** [comment]
Could I get the full error log instead of just those lines?

**Comment by Dirt998** [comment]
@TheWinABagel I am getting the same Error and it crashes on start up. I have attached the error log from the First Error that it gives to the end of the log. 
[ZenithErrorLog.txt](https://github.com/TheWinABagel/Zenith/files/11392763/ZenithErrorLog.txt)

**Comment by TheWinABagel** [comment]
If you have the version of porting lib from Curseforge remove it as it is horribly out of date, there's a much more recent version in Zenith @Dirt998

**Comment by Dirt998** [comment]
I removed the porting_lib that I downloaded off of Curseforge and it fixed my issue. Thank you so much! @TheWinABagel

**Comment by TheWinABagel** [comment]
Closed as there isn't enough info
