### ISSUE TITLE
Version 1.2.0 & 1.2.1 crash on startup

### ISSUE THREAD

**Issue by Captivename** [TheWinABagel/Zenith#183]
Both versions listed above crashing on startup. Below is the crash report for version 1.2.1 one is not generated for 1.2.0.

[crash-2024-07-09_14.42.02-client.txt](https://github.com/user-attachments/files/16144157/crash-2024-07-09_14.42.02-client.txt)

Version 1.1.10 working with current mods so I'm guessing the update introduces a conflict somewhere but I'm not knowledgeable enough to identify the conflict.

**Comment by Captivename** [comment]
The conflict seems to be with the [Zephyr mod](https://www.curseforge.com/minecraft/mc-mods/zephyr)  as when it's disabled Zenith version 1.2.1 loads correctly.

**Comment by muon-rw** [comment]
Was a mixin issue with Zephyr - fixed in 0.5.0
