### ISSUE TITLE
Game crash after 1.2.1 update

### ISSUE THREAD

**Issue by KuschelKaktus88** [TheWinABagel/Zenith#184]
after updating the zenith mod to 1.2.1 version the game crashes immeadiatley on interaction with the salvaging table and the gem cutting table

**Comment by Starior** [comment]
[crash-2024-07-11_00.19.52-client.txt](https://github.com/user-attachments/files/16169061/crash-2024-07-11_00.19.52-client.txt)
[crash-2024-07-11_00.25.16-client.txt](https://github.com/user-attachments/files/16169108/crash-2024-07-11_00.25.16-client.txt)
When trying to move a gem into a table cell

**Comment by Grimmspecter** [comment]
Would also like to notate it seems to crash in zenith UIs and seems to be a client issues dedicated server doesnt through errors or crash just the clients

**Comment by TheWinABagel** [comment]
Fixed with 1.2.2
