### ISSUE TITLE
Anvil Splitting / Obliteration not working yet

### ISSUE THREAD

**Issue by SiverDX** [TheWinABagel/Zenith#2]
Hello,

**Background**:
* Running on a server
* World was created with `zenith-0.4.31.19.2.jar` and later updated to `zenith-0.5.1+1.19.2.jar`
* Modpack used: https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric

**What I noticed**:
* I can enchant an anvil
* An anvil can have Obliteration and Splitting at the same time - is this intended?
* The default anvil is now from `Zenith` (no longer from `Minecraft`) (not sure if this is relevant)
* When I drop an anvil on a book, nothing happens - the book stays the same
* When I try to pick up the anvil (with and without `Silk Touch`) I receive an anvil with no enchants (`Unbreaking`, `Obliteration` and `Splitting` all disappear)
* I created a new world in singeplayer and it did not work there either

Is the anvil supposed to show an enchantment glow when it is placed down?
Even when falling it looks like a normal anvil - maybe the enchantments already get removed once you place it down (in the air / on the ground)?

**Comment by Frontear** [comment]
Developer has said EasyAnvils is causing a conflict. Please try removing that mod and testing again

**Comment by TheWinABagel** [comment]
Fixed even when EasyAnvils is installed in the next version (0.5.3)
PS Anvil being from zenith is intentional and the anvil being able to have obliteration and Splitting at the same time are both intentional
