### ISSUE TITLE
Additonal Bookshelf variets added from other mods under #c:bookshelf not counting as a valid shelf to zenith enchanting table

### ISSUE THREAD

**Issue by Shibva** [TheWinABagel/Zenith#21]
Not sure how id word this but I think its self explanitory from these images

<img width="453" alt="image" src="https://user-images.githubusercontent.com/38770780/235900316-4a3a67a8-e6c8-4a68-817e-f59ce101c8d3.png">
<img width="725" alt="image" src="https://user-images.githubusercontent.com/38770780/235900362-517d207f-d6ab-450a-9266-89d9423ba41d.png">
<img width="767" alt="image" src="https://user-images.githubusercontent.com/38770780/235900441-4e5af8c5-c04c-409f-822b-656f2e85cb84.png">

**Comment by Shibva** [comment]
and just to be clear im referring the default base value for a normal bookshelf not being applied to the others that are under #c:bookshelf

**Comment by TheWinABagel** [comment]
Hmm, yeah looks like the json serializer isn't reading tags properly... will look into it when I have some more time

**Comment by xanthian** [comment]
Any chance this could be picked up?
My variant bookshelf mod does not work with zenith either, seems only zenith shelves and the vanilla one works.

Or alternatively, how can I add zenith support?

**Comment by TheWinABagel** [comment]
Already been fixed in 1.20 for a while, will be fixed in 1.19 in the next update (today or tomorrow).
