### ISSUE TITLE
[Crash] When using Sodium, reforging items crashes if the item is a shield or is enchanted

### ISSUE THREAD

**Issue by Hexicube** [TheWinABagel/Zenith#226]
`Caused by: java.lang.IllegalArgumentException: The class dev.shadowsoffire.apotheosis.adventure.client.GhostVertexBuilder does not implement interface VertexBufferWriter, which is required for compatibility with Sodium (see: https://github.com/CaffeineMC/sodium-fabric/issues/1620)`

Disabling Sodium obviously fixes this, but it should also hopefully be a simple fix.

**Comment by TheWinABagel** [comment]
Update sodium, that's been fixed for a while

**Comment by Hexicube** [comment]
Right, now to bang my head against a wall because Immersive Portals wanted a specific version of Sodium.
