### ISSUE TITLE
Sigil of Unnaming Recipe crafts a Sigil of Withdrawal instead

### ISSUE THREAD

**Issue by f-raZ0R** [TheWinABagel/Zenith#227]
https://github.com/TheWinABagel/Zenith/blob/1.20/src/main/resources/data/zenith/recipes/sigil_of_unnaming.json
This results in the sigil of unnaming being unobtainable

**Comment by TheWinABagel** [comment]
Oops

**Comment by TheWinABagel** [comment]
Will be fixed in next release
