### ISSUE TITLE
Unable to go past vanilla enchantment level limit in anvil

### ISSUE THREAD

**Issue by raf59324** [TheWinABagel/Zenith#23]
Maximum level for enchantments are not increased from vanilla minecraft in the Fabric version, unlike in Apotheosis.

**Comment by raf59324** [comment]
Correcting this post; max enchants are increased - the crafting recipes are not working

**Comment by TheWinABagel** [comment]
Are you on quilt? Theres a PR open (#14) to fix zenith not working with quilt but its low priority for me right now

**Comment by raf59324** [comment]
Nope, not on quilt - on Fabric; but I did check that and it seems to be the same issue. Running quite an extensive modlist, so unsure as to what might be causing issues. REI does not display any enchanted books nor potions from Zenith; yet when in the enchanting table you are still able to acquire them. But in smithing, you also can't combine books of the same enchant to get one of a higher level.

**Comment by TheWinABagel** [comment]
Hmm, that anvil combining issue is also in the Medieval minecraft modpack, could you send a modlist so I can compare? or export the pack from your launcher

**Comment by raf59324** [comment]
https://pastebin.com/PYyY44Kq

Here is the entire modlist!

**Comment by TheWinABagel** [comment]
The anvil combining issue should be fixed in the latest version, as with the crafting recipe issue, but REI not rendering zenith items is super weird, not sure what that's about

**Comment by raf59324** [comment]
Doesn't seem to be fixed for us sadly, Protection IV + Protection IV = Protection IV still, anvil not allowing to go past vanilla minecraft limits.

**Comment by TheWinABagel** [comment]
I'll have to take an in depth look at this once I have time, not for the next two weeks though as I am going out of town and most likely wont be working on this

**Comment by raf59324** [comment]
No worries, thank you very much for your work with this port :)

**Comment by totrider** [comment]
Can confirm, having the same issue with my custom modpack on a server.

Server is running V1.3.9 of Dragon Claw Adventure 1 https://www.curseforge.com/minecraft/modpacks/dragon-claw-adventure-1/files

With these additional files (due to some being moved to Modrinth)
![image](https://github.com/TheWinABagel/Zenith/assets/1184655/c88dfba0-b820-45d2-97cf-a3806a9335c8)

**Comment by TheWinABagel** [comment]
It was an incompatibility with goblin traders, fixed in 0.6.3
