### ISSUE TITLE
Zenith's Spawner Module causes a crash if Spirit is installed (even when disabled in the config)

### ISSUE THREAD

**Issue by globalista-dev** [TheWinABagel/Zenith#24]
Minecraft Version: 1.19.2
Zenith Version: zenith-0.5.7+1.19.2

I disabled Zenith's Spawner Module because I'm using Spirit. When I break a Spawner, the game crashes. Spirit adds a Spawner drop (Broken Spawner), and I think Zenith does as well. 

Crash Report: https://mclo.gs/Um25N7c

I downloaded the source code and removed the Spawner module entirely and the crash no longer happens. This isn't a fix, obviously, just letting you know.

**Comment by Shibva** [comment]
confirm bug. It seems the issue was caused because of something with the Capturing Enchantment (for some reason...)

**Comment by Shibva** [comment]
UPDATE: tested wtih the lattest release that fixes spawner shit; Issue is no longer present wtih Spirit wtih module disabled

Please test on your end to confirm @globalista-dev

**Comment by globalista-dev** [comment]
Fixed on version zenith-0.5.9+1.19.2! Closing the issue and marking it as solved. Thanks for letting me know @Shibva!
