### ISSUE TITLE
Scavenger, Spearfishing, and Knowledge do not activate

### ISSUE THREAD

**Issue by DragonOfMath** [TheWinABagel/Zenith#25]
Zenith enchantments related to loot drops are not being used after [updating porting-lib from build 706 to 815](https://github.com/TheWinABagel/Zenith/commit/382b490617ce19ea6d1e7cc8de8c2b20c6682c5c).

https://github.com/TheWinABagel/Zenith/blob/edefb3408726f0c3f46e56fb3551833324a5576c/src/main/java/safro/zenith/ench/EnchModuleEvents.java#L44

Might this have something to do with Porting-Lib deprecating `LivingEntityEvents.DROPS_WITH_LEVEL` in favor of `DROPS` for 1.19.3?

https://github.com/Fabricators-of-Create/Porting-Lib/commit/8126f00e0d8cff8ae2bcebc14d8c9e55f19b1488#diff-eee0f0050aa5fd3d598d3912740649ee67611c039e917e2748f9ee4de9b79105

If so, revert to a porting-lib build version for 1.19.2 or use the preferred event.

**Comment by pontorka** [comment]
I have this issue, but I don't have porting-lib installed

**Comment by TheWinABagel** [comment]
It isn't depreciated in 1.19.2, so I don't fully understand what the issue here is... the enchantments work properly as of right now as far as I know, once I update the mod to 1.20 I'll change it over to the new event names
