### ISSUE TITLE
No way to automatically insert into enchantment library / of alexandria

### ISSUE THREAD

**Issue by BracketMaan** [TheWinABagel/Zenith#26]
Currently there is no way to automatically insert enchanted books into the library. Hoppers, ae2 export buses, modern industrialization pipes, modern dynamics.. Nothing works. 
Not sure if not implemented yet or a bug but i'm playing on the pack All Of Fabric 6 and manually added this mod in.

**Comment by TheWinABagel** [comment]
This isn't implemented as of right now, and it isn't very high on my to do list as of right now as I would have to rewrite how the library is implemented

**Comment by TheWinABagel** [comment]
Finally added in 1.0.3
