### ISSUE TITLE
Zenith shelves requiring potions, show up needing Uncraftable Potion in REI and uncrafting bench returns wrong potion too

### ISSUE THREAD

**Issue by totrider** [TheWinABagel/Zenith#29]
REI shows that you need the "Uncraftable Potion" to make any of the Zenith shelves. The Twilight Forest Uncrafting Bench will also give the player "Uncraftable Potion" instead of the correct one for each shelf type. To craft the shelves, you still need the correct potion type, e.g. potion of regeneration for the Hellshelf.

Sounds similar to this issue: https://github.com/Safrodev/Zenith/issues/25

This all happens on a server, have not tested in singleplayer yet. Server is running V1.3.9 of my own modpack Dragon Claw Adventure 1 https://www.curseforge.com/minecraft/modpacks/dragon-claw-adventure-1/files

With these additional files (due to some being moved to Modrinth)
![image](https://github.com/TheWinABagel/Zenith/assets/1184655/c88dfba0-b820-45d2-97cf-a3806a9335c8)

**Comment by TheWinABagel** [comment]
Fixed with 0.6.2
