### ISSUE TITLE
No bonus for candles or skeleton skulls

### ISSUE THREAD

**Issue by SiverDX** [TheWinABagel/Zenith#3]
Hello,

I saw in the known issue that `Fix candles and weaker skulls not working` is marked as done
But for me it is not working yet

**Background**:
* Running on a server
* World was created with `zenith-0.4.31.19.2.jar` and later updated to `zenith-0.5.1+1.19.2.jar`
* Modpack used: https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric

**What I noticed**:
* Candles and skeleton skulls have no tooltip describing their bonus (the tooltip was correctly added to other items like `Seashelf`)
* They provide no bonus to `Quanta` or `Arcana`
* When I create a new world (tested in singeplayer) the items have the correct tooltips

My assumption is that the update will not retroactively fix these two items on an existing world, is that correct?

**Comment by TheWinABagel** [comment]
Fixed as of 8708f5a
