### ISSUE TITLE
Anvil crashes game when inserting enchanted item

### ISSUE THREAD

**Issue by totrider** [TheWinABagel/Zenith#32]
Have a Runic pickaxe (Mythic Metals) with an enchantment. Release item into anvil slot crashes the client. Removing Zenith fixes problem. Enchanting module is disabled.

Running Dragon Claw Creations 2 V0.4 https://www.curseforge.com/minecraft/modpacks/dragon-claw-creations-2/files

Crash log: https://pastebin.com/2Nbdbgh0

**Comment by totrider** [comment]
I just did a test, and it seems to happen if the enchantment module is set to "false" in the config. Setting it to "true" in a wolrd that would crash before, resolves the issue and the item can be placed without crashing the game.

**Comment by TheWinABagel** [comment]
Fixed with release 0.6.3

**Comment by totrider** [comment]
> Fixed with release 0.6.3

Nope, still causing a crash on 1.19.2 using Zenith 0.6.3

https://pastebin.com/yyYuWfRM
