### ISSUE TITLE
"Compatibility" request - EasyMagic 

### ISSUE THREAD

**Issue by muon-rw** [TheWinABagel/Zenith#4]
When both EasyMagic and Zenith are installed, The Zenith enchanting GUI does not load. 

Assign loading priority over EasyMagic, or list as an incompatibility for clarity.

**Comment by TheWinABagel** [comment]
With the current implementation, this is not possible as zenith requires the vanilla tile entity and EasyMagic overrides it; It would be a pain to fix in a meaningful way. I'll make a note on curseforge that it isn't compatible though
