### ISSUE TITLE
[Farbic & Quilt 1.19.2] Charms have Durrabilty Loss logic backwards

### ISSUE THREAD

**Issue by Shibva** [TheWinABagel/Zenith#40]
Title should be self-explanatory; but just in case

Charms when used in survival don't lose durrabilty but when in creative they do.

I think you might have flip-flopped that logic by accident 🤣

**Comment by Shibva** [comment]
Should be a simple flip-flop to unflip the flip-flop. (swapping it should swap it back to normal)

**Comment by TheWinABagel** [comment]
Its always the little things...
Will be fixed next update (whenever that is... been feeling some burnout on this as of late)

**Comment by TheWinABagel** [comment]
This was fixed a while ago, I just forgot :P

**Comment by Shibva** [comment]
@TheWinABagel You forgot to include in the change log lol
