### ISSUE TITLE
[Minor] Bambo Height config not working/broken

### ISSUE THREAD

**Issue by Shibva** [TheWinABagel/Zenith#45]
I set bamboo to grow up to 24

The mod: (crap, creeper blew me up before I could get the shot, so take this shot of how much I got when I broke the 2 bamboo plants I planted)
![image](https://github.com/TheWinABagel/Zenith/assets/38770780/6231672d-22c0-4ee0-8a50-54f6e625f6c1)
nuff said lel

**Comment by TheWinABagel** [comment]
This is supposed to be the tiny module with no issues aaaa
will be fixed.

**Comment by TheWinABagel** [comment]
Finally (really really late) fixed it in 1.19
