### ISSUE TITLE
[Minor: Text dialog for "Limited Enchantability" broke & Deepshelf missing lootable

### ISSUE THREAD

**Issue by Shibva** [TheWinABagel/Zenith#49]
![image](https://github.com/TheWinABagel/Zenith/assets/38770780/ff6d5a2f-fc65-48ae-a2db-3126adf082c2)
hmmm

ya know I might be able to fix this

**Comment by Shibva** [comment]
and I just found that deepshelf dosent drop anything when you break it

**Comment by AlexanderRyb** [comment]
Worth noting it's not just text, I can't enchant it even though I have the 60 levels

**Comment by Shibva** [comment]
That message usually means that you don't have the right set up to do certain things

For example: if you're trying to make a infused to hell shelf, then you need to have certain minimum stats. Otherwise it's not going to work.

**Comment by Shibva** [comment]
Closing repo; there are still a few things broken though that I have missed; just to make note.
