### ISSUE TITLE
[Fix] ToolTip fix for mods that break Masterwork, Twisted, & Corrput Echantment name colors

### ISSUE THREAD

**Issue by Shibva** [TheWinABagel/Zenith#51]
https://github.com/TheWinABagel/Zenith/commit/1d64cdb1db52612bd19b4b261d2346b91e3014f5

This is an experimental fix that I have tested with my pack and fixes an issue I had caused by some unkown mod in this pack that makes the colored text for Masterwork, Twisted, & Corrput to instead be registered without its unique colors,

This is done by adding format codes into the string of the lang

This complies with merge request #50's changes to the lang file.

NOTE: this fix might be considered aggressive; though I'm not sure. it does force these enchant names' color to be maintained no matter what.

If you wish for this to be applied; respond to this with a message and ill create/update my current pull request to include it

**Comment by Shibva** [comment]
Update: this fix appears to not account for level numbers
![image](https://github.com/TheWinABagel/Zenith/assets/38770780/965841b5-7f96-48b3-b549-7bdc511a50c8)

**Comment by TheWinABagel** [comment]
I don't see a reason why not, I might add it to the 1.20 version I'm working on as well (I'm re-porting the entire mod as the current state of zenith 1.19 is bandaid fix after bandaid fix)
I'm not sure how much I'll be maintaining the 1.19 version afterwards, I don't want to completely drop it but working with a fresh port is much less painful lol

**Comment by TheWinABagel** [comment]
I've also kind of been neglecting the issues on this repo... I'll get to this and some of the other issues in the next few days hopefully

**Comment by Shibva** [comment]
Welcome back lel
