### ISSUE TITLE
[Possible Bug] Life Mending possibly not working correctly 

### ISSUE THREAD

**Issue by Shibva** [TheWinABagel/Zenith#52]
Im aware that changes to how Life-Mending works were made but I'm unsure if its working correctly

currently, if you regain HP you regain durability; the question is, is it supposed to prevent the player from regaining HP while it's held??

**Comment by TheWinABagel** [comment]
Yeah imma be honest the current implementation of life mending (and the potions that effect healing) is absolute garbage, I need to replace the thing with an event instead of the cursed mixin

**Comment by Shibva** [comment]
It is somewhat working; it's just you are still getting HP back when in an active slot (when you shouldn't)

**Comment by TheWinABagel** [comment]
Fixed in 1.19, with version 0.7.2
