### ISSUE TITLE
[Bug] Capturing not appearing on Enchant module's Enchant control list

### ISSUE THREAD

**Issue by Shibva** [TheWinABagel/Zenith#54]
The issue is right to the point; for some reason Capturing is not added to the Enchanter configuration, making it impossible to configure its occurrence values and such

**Comment by Sooperfish** [comment]
~~Probably related to #107, as I get `Registry entry (zenith:capturing) is missing from local registry (minecraft:enchantment)~~
i had the spawner module disabled

**Comment by TheWinABagel** [comment]
Fixed in 1.19 (been fixed in 1.20 for ages)
