### ISSUE TITLE
Disabling spawner upgrades?

### ISSUE THREAD

**Issue by Iveess** [TheWinABagel/Zenith#55]
Is there any way to disable spawner upgrades? the server administration considers it a strong problem to improve spawners, as well as the ability to collect them with a silk touch and insert mob eggs into them. I know that in the configs you can turn off the digging of spawners and you can make it so that no egg can change the mob in the spawner, but I want to know if it is possible to completely disable, in addition to these two features, the improvements of spawners? Server administrators are ready to accept the mod without the spawner feature, but neither they nor I know how to remove it.

**Comment by muon-rw** [comment]
You can simply disable the spawner module completely. Check /config/zenith/zenith.cfg

**Comment by Iveess** [comment]
Thanks, that help us
