### ISSUE TITLE
Mixin conflict in 1.20

### ISSUE THREAD

**Issue by noah1510** [TheWinABagel/Zenith#56]
When I try to add zenith for minecraft 1.20 I get some nasty mixin conflicts.

This is the crash report:
[crash-2023-10-15_00.58.50-client.txt](https://github.com/TheWinABagel/Zenith/files/12908168/crash-2023-10-15_00.58.50-client.txt)

And this is the log file:
[2023-10-15-5.log](https://github.com/TheWinABagel/Zenith/files/12908171/2023-10-15-5.log)

The problem is only detected after everything is loaded.
Usually the main menu is visible after the mouse wheeli log message but instead the game crashes with the given crash report.

fakerlib alone does not cause the problem neither does zenith attributes.
Only when adding zenith the game crashes.

**Comment by TheWinABagel** [comment]
Will be fixed next release, looks to be an easy fix

**Comment by TheWinABagel** [comment]
Fixed
