### ISSUE TITLE
Mod Incompatibility: Hephaestus

### ISSUE THREAD

**Issue by Vinesauced** [TheWinABagel/Zenith#58]
Crashes on startup
Version: 1.20.1
Zenith Version: 0.1.1-1.20.1
Mods: Only Hephaestus and Zenith (with fakerlib and attributes) both mods work fine independently
MC Log: https://mclo.gs/hKX6nvf
MC Crash report: https://mclo.gs/ZprEnJ2

Edit: just realized how out of date Zenith was, updated and I get the same issue
Second Edit: Same crash report appears when using Zenith and Create

**Comment by TheWinABagel** [comment]
Unfortunately they aren't compatible at the moment as the version of porting lib that I'm currently using is incompatible with the version used by Hephaestus, I don't know when this will be fixed.
That being said, there should be versions of create that work fine with this version of porting lib, not sure why you're having issues

**Comment by TheWinABagel** [comment]
I was just made aware of a potential solution to this, called [tamango](https://modrinth.com/mod/tamago). Install it in mods folder like a normal mod and things should work? Just a note that I haven't tested this personally, was told it works though

**Comment by TheWinABagel** [comment]
That being said, I do plan on updating to the latest porting lib here within the next week or two so it will be compatible by default

**Comment by Neubulae** [comment]
Same issue occurs, tamango doesn't(or rather, failed to) fix this issue. I'm using [PortingLib 2.1.1163](https://modrinth.com/mod/porting_lib/version/2.1.1163+1.20.1)

**Comment by TheWinABagel** [comment]
It's been a bit longer than the promised week or two (got surprisingly busy with life stuff after that comment), but Zenith on latest porting lib is coming soon, which will fix this incompatibility

**Comment by tiigerbones** [comment]
any good news on the port lib updates?

**Comment by TheWinABagel** [comment]
I have a fork using it made, need to do some cleanup first but I would be shocked if it took me more than a week to get it finished

**Comment by NotZoeyDev** [comment]
Look forward to it, been making a fabric modpack over here and it would be awesome to get Hephaestus compat working soon

**Comment by windy664** [comment]
[crash-2024-03-08_18.15.10-client.txt](https://github.com/TheWinABagel/Zenith/files/14536871/crash-2024-03-08_18.15.10-client.txt)

**Comment by TheWinABagel** [comment]
Updated to lastest porting lib, finally! Update to 1.1.0 for it
