### ISSUE TITLE
Can't join server with adventure module enabled

### ISSUE THREAD

**Issue by PineappleCat22** [TheWinABagel/Zenith#59]
Version: 1.20.1
Zenith: 0.1.2
Zenith-Attributes: 0.0.3
fakerlib: 0.0.6
Server log: https://mclo.gs/i9oXmPg
Client log: https://mclo.gs/yk1RAGJ

As title says, cant join server with zenith on it. 
Successfully able to join after disabling the adventure module in the config, but there's no fun in that.

**Comment by TheWinABagel** [comment]
I figured there would be a problem with servers, hmm...
Seems to be a packet issue, hence the only happening on servers, should have a release out soon to fix it

**Comment by TheWinABagel** [comment]
Fixed, update to Fakerlib 0.0.7 (Zenith doesn't need to be updated)
