### ISSUE TITLE
(Bug) Reforging tables and salvaging table uncraftable

### ISSUE THREAD

**Issue by Cocopa99** [TheWinABagel/Zenith#60]
Cannot craft either reforging table or the salvaging table using their respective recipes.

**Comment by L0tsu** [comment]
Same here !
We have the v0.1.4 1.12.1 and for some reason i seem to not be able to craft the salvaging table or the reforging table, is there something in the config to change or is there straight up just a bug with the mod ?

**Comment by TheWinABagel** [comment]
Yeah, that was my bad, forgot to change a tag from the forge one to the fabric one. Fixed as of 0.1.5
