### ISSUE TITLE
Mod Incompatibility: Dungeon Difficulty

### ISSUE THREAD

**Issue by Cocopa99** [TheWinABagel/Zenith#62]
For some reason when the Dungeon Difficulty mod is installed with yours it causes ticking entity errors for certain mods.  The two I caught were guard villigers and rare ice.  Not sure if this issue is even fixable on your end but Im linking both crash logs for the respective mods

[Guard Villigers Crash.txt](https://github.com/TheWinABagel/Zenith/files/13060211/Guard.Villigers.Crash.txt)
[Rare Ice.txt](https://github.com/TheWinABagel/Zenith/files/13060212/Rare.Ice.txt)

**Comment by TheWinABagel** [comment]
Both dungeon difficulty and the adventure module are kind of doing the same thing to the item to a certain extent, but I'll look into it to see if there's a fix
