### ISSUE TITLE
Sugustion: add cofig for the avalability of unbreakable charms

### ISSUE THREAD

**Issue by UnnaturalTwilight** [TheWinABagel/Zenith#64]
I would love to be able to turn off making potion charms unbreakable separately form charms as a whole when balancing my modpack.
Version: 0.7.1+1.19.2

**Comment by TheWinABagel** [comment]
The recipe can be disabled via datapack. See [here](https://github.com/TheWinABagel/Zenith/blob/1.19/src/main/resources/data/zenith/recipes/enchanting/potion_charm_enchanting.json) for the location of the JSON.
