### ISSUE TITLE
Unable to put hoe into reforger

### ISSUE THREAD

**Issue by jonask028** [TheWinABagel/Zenith#65]
On 1.20.1 i am unable to place my diamond hoe into the reforger to get an epic tier affix. I can place my pickaxe in it and it gives me the option to reforge but not the hoe.

**Comment by jonask028** [comment]
looked into the java files and the breaker class is missing hoes and shears

**Comment by TheWinABagel** [comment]
Hoes are not part of an affix group by default, if you want to add them to one use the type override in the config
