### ISSUE TITLE
porting_lib.swim.speed

### ISSUE THREAD

**Issue by glea94** [TheWinABagel/Zenith#68]
Hi, i can't get the attribut for the swim boost and the height foot step.
I have the last update zenith-0.1.11-1.20.1.jar for Fabric
Thank you
![2023-11-10_13 23 53](https://github.com/TheWinABagel/Zenith/assets/89050166/a0083b7c-63c2-4596-9c75-275fbc7b6d6b)
![2023-11-10_13 27 27](https://github.com/TheWinABagel/Zenith/assets/89050166/9f776b03-7691-4c60-90bb-a1f3f80946fe)

**Comment by TheWinABagel** [comment]
Fixed in 0.2.0, make sure to update Zenith Attributes as well

**Comment by glea94** [comment]
Hi i just launch the game today and made an update, thank you ^^ it works fine now😘
