### ISSUE TITLE
Vial of Arcane Extraction does not work on smithing table

### ISSUE THREAD

**Issue by iteathen** [TheWinABagel/Zenith#69]
zenith-0.1.5-1.20.1

This seems to also be a bug in Apotheosis.

https://github.com/Shadows-of-Fire/Apotheosis/issues/1016

**Comment by AuxAtlas** [comment]
I submitted a PR to the official apotheosis located [here ](https://github.com/Shadows-of-Fire/Apotheosis/pull/1073) with required changes to fix the issue.

**Comment by TheWinABagel** [comment]
Implemented that PR, fixed in 0.2.0
