### ISSUE TITLE
Compatibility - BetterX (anvils)

### ISSUE THREAD

**Issue by muon-rw** [TheWinABagel/Zenith#7]
The Cincinnasite Anvil says it can be enchanted, but can not

![image](https://user-images.githubusercontent.com/128171313/231039923-e8ddf2da-cb75-4f11-aac4-b44121878dd4.png)
![image](https://user-images.githubusercontent.com/128171313/231039910-58b7c22d-7a45-4e99-964a-a4dd5e1b337c.png)

The Better End Anvils also can not be enchanted, but have no tooltip (and may have some differing mechanics, I don't think this would be important to change)

![image](https://user-images.githubusercontent.com/128171313/231040596-8c899402-e628-4bea-9c13-9240cc568006.png)

**Comment by TheWinABagel** [comment]
Added cincinnasite anvil to list in fd37e40, I wont support the better end anvils as they're custom in some capacity
