### ISSUE TITLE
Spawners lossing data after pickup/placement

### ISSUE THREAD

**Issue by antuar-ramos** [TheWinABagel/Zenith#70]
When picking up a spawner (rogue or dungeon) it losses it's original data regarding what mob it spawned and the stats it had, leaving an empty spawner in it's place

**Comment by TheWinABagel** [comment]
What mod version are you using? And could you send your mod list?

**Comment by antuar-ramos** [comment]
Mod version is Zenith 0.1.7 - 1.20.1
The mod list of the server running the world:

- Bookshelf-Fabric-1.20.1-20.1.6.jar
- cardinal-components-api-5.2.2.jar
- cloth-config-11.1.106-fabric.jar
- EnchantmentDescriptions-Fabric-1.20.1-17.0.8.jar
- fabric-api-0.90.4+1.20.1.jar
- fabric-carpet-1.20-1.4.112+v230608.jar
- fakerlib-0.0.7.jar
- InventorySorter-1.9.0-1.20.jar
- Jade-1.20-fabric-11.6.2.jar
- lithium-fabric-mc1.20.1-0.11.2.jar
- no-telemetry-1.7.0.jar
- Patchouli-1.20.1-81-FABRIC.jar
- sodium-fabric-mc1.20.1-0.5.3.jar
- travelers-backpack-1.20.1-9.1.6.jar
- zenith-0.1.7-1.20.1.jar
- zenith_attributes-0.0.4.jar

**Comment by antuar-ramos** [comment]
Updated the mod and its dependencies (fakerlib, zenith attributes) to the latest available (fakerlib-0.0.9, zenith-0.2.0-1.20.1, zenith_attributes-0.1.0) and the bug is present, when you pick up a spawner it displays correct on the inventory (correct entity and stats) but losses all data when placed on the world

**Comment by TheWinABagel** [comment]
Try with 0.2.2, it should be fixed now

**Comment by antuar-ramos** [comment]
Yes is fixed now, thanks for the help.

Quick question on a different topic, are rogue spawners implemented?
