### ISSUE TITLE
[Bug] Librarian Villager's trade and Vanilla Structure's Loot not affect by the "Max Loot Level" in config

### ISSUE THREAD

**Issue by Clown18168** [TheWinABagel/Zenith#72]
In Apotheosis, changing the max loot level in the enchantments config also changes the max level available from trading with librarian Villager. But after testing, it seems like changing the number only has an effect on the loot from the tower in the Zenith mod, it has no effect on both loot from vanilla structure(Mansion, Fortress, etc) and trading with a librarian.

**Comment by TheWinABagel** [comment]
Villager one wasn't implemented (fixed in 0.2.1), but the loot chests should give it fine... odd

**Comment by TheWinABagel** [comment]
Nevermind, figured it out
Will be fixed in 0.2.1
