### ISSUE TITLE
Mod "Zenith"  Conflicts with the mod "easy anvils"

### ISSUE THREAD

**Issue by MAHUNDR** [TheWinABagel/Zenith#74]
Minecraft: 19.2 FABRIC
Mod: zenith-0.7.1+1.19.2

After installing these two mods, the anvil does not receive any changes from the mod "easy anvils".

**Comment by TheWinABagel** [comment]
Zenith and Easy Anvils both override behavior for the anvil, not much can be done to make them compatible.
