### ISSUE TITLE
crash on world creation on version 2.3 

### ISSUE THREAD

**Issue by eldritch-cookie** [TheWinABagel/Zenith#76]
basically according to the log [this line](https://github.com/TheWinABagel/Zenith/blob/e54d444e2c655c82ad08e62111daff872b7234b2/src/main/java/dev/shadowsoffire/apotheosis/adventure/affix/socket/gem/bonus/special/AllStatsBonus.java#L51C108-L51C108) is problematic as attribute lib 0.1.1 removes this field from the class https://github.com/TheWinABagel/ZenithAttributes/commit/6ae46288629ab50bc1d0d6b0f1527e324834d138
https://gist.github.com/eldritch-cookie/96b3b0979e2889bab516826ab9accfde

**Comment by TheWinABagel** [comment]
Yeah whoops, fixed in 0.2.4
