### ISSUE TITLE
Enchanting Table won't open in Survival

### ISSUE THREAD

**Issue by Simiux** [TheWinABagel/Zenith#78]
I am unsure what mod in junction with Zenith is causing the Enchanting table only to open in Creative mode.

I checked even de level.dat files, and deleted all configs. Granted I had Easy Magic on, which I removed all traces of.

These are the mods I'm currently running:

MC Dungeons Weapon + Enchantments
Cloth Config API
Fabric API
Interactic
Loot Beams
REI
OwO Lib
Mine Cells
FallingTree
Zenith
Spell Power Attributes
Runes
AzureLib
Jewerly
Paladins & Priest
Terralith
BCLIB
Nullscape
Better End
Iris Shader
Corgilib
Terra Blender
Farmer's Delight
Adv. Plaques
Lootr
Traveler's Titles
CT's Overhauld Village
Dungeons Arise
Traveler's Backpack
Knave's Needs
Architectury API
Simply Swords
Cardinal Components API
Custom Portals
libIPN
Fabric Language Kotlin
Inv Profiles Next
Legendary Tooltips
More Culling
Entity Culling
BetterNether
Elytra Slot
Botania
Trinkets
Simple Hats
Immersive Armors
Neat
CreativeCore
AmbientSounds 5
Patchouli
Puzzles Lib
Convenient Decor
Forge Config API Port
Prism
Iceberg
Easy Magic
Beautify
Dramatic Doors
BetterAdvancements
Mythic Mounts
Sprout
Warden Horn
Deeper Darker
Wizards
Gecko Lib
Nyf's Spiders
Bookshelf Fabric
Convenient Mobgriefing
Yung's Better Mineshaft
Yung's Better Strongholds
Yung's Better Dungeons
Yung's Better Desert Temple
Yung's Better Ocean Monuments
Yung's Better WItch Huts
Yung's Extras
Yung's Bridges
Yung's Better Nether Fortresses
Yung's API
Xaero's World Map
Xaero's Minimap
WI Zoom
Friends & Foes
Show Me Your Skin!
Nature's Compass
Ribbit
Mod Menu
Lithium
Inventory HUD+
Terra Fabric
Enchantment Desc.
Effortless Fabric
Dungeon Difficulty
Do A Barrel Roll
Combat Roll
Player animation
Better Combat
Appleskin
Starlight
Sodium
Spell Engine
Pufffish Skills
Simplyskills
TieredZ
libz
Autotag
Gear Core
Fuzzy Core
Gearifiers
MC Dungeons Armor
MC Dungeons Artifacts
Projectile Damage
Marium's Soulslike
Diagonal Windows
Diagonal Fences
Waystones
Medieval music
Biome music
Origins
Origins++
Healingcampfire
Stylish effects
Pickup notifier
Magnum torch
Shoulder surfing
Elytra recast
Endermanoverhaul
Tiny Skeletons
Zenith Attributes
Zephyr

**Comment by Simiux** [comment]
Figured out the Issue, it wasn't anything zenith mod related.

The Mod Minecraft Dungeons Enchantment has a setting in their config that blocks enchantment use?? and this isn't specified on their modpage that it's off by default.

"allowUsingEnchantingTable": false,
	// Sets cost of gilding
	"gildingCost": 8,
	/* Each n-th tick (where n is this setting) would increment progress of gilding.
	   The process consists of 33 steps (frames). So, overall process would take n * 33 ticks.
	*/

**Comment by TheWinABagel** [comment]
Thats... odd. I'll keep it in mind if anyone asks about a similar issue
