### ISSUE TITLE
Ender Lead Mobs Poof Gone

### ISSUE THREAD

**Issue by LeDalahast** [TheWinABagel/Zenith#79]
Playing on the mod pack "Prominence II" and a few of our users have a issue when placing down their mob from the lead.
After a mob has been picked up when placing,  the sound for placing it plays but then no mob appear and it becomes empty.
Any ideas if there is a fix our could it be another mod that is making this happen?

**Comment by TheWinABagel** [comment]
I'll look into it, It's most likely a mod incompat of some sort

**Comment by TheWinABagel** [comment]
What mob was this? I can't reproduce this in Prominence II

**Comment by BushTrocity** [comment]
I have had it happen with the zar-ptak and the dragon

**Comment by TheWinABagel** [comment]
Cannot reproduce
