### ISSUE TITLE
Registry remapping failed after update

### ISSUE THREAD

**Issue by ikkytavy** [TheWinABagel/Zenith#8]
updating from 4.4 to 5.5 I get an error. 
![image](https://user-images.githubusercontent.com/116700130/231319902-d0bd3136-6334-471e-9d75-4006350accda.png)

**Comment by muon-rw** [comment]
Do you have the same version of Zenith on client and server?

**Comment by ikkytavy** [comment]
Yeah that was my problem. I'm a dum-dum lol. Thanks!
