### ISSUE TITLE
Fire Aspect breaks Knowledge of the Ages

### ISSUE THREAD

**Issue by lmvdz** [TheWinABagel/Zenith#80]
Zenith-0.2.3-1.20.1
ModPack: Prominence2

After putting Fire Aspect on my weapon, the drops no longer are turning into Experience.
![image](https://github.com/TheWinABagel/Zenith/assets/2179775/a7626697-4332-4991-91b4-5b6738b5099d)

**Comment by lmvdz** [comment]
Removed the Fire Aspect and confirming that was the issue.

**Comment by lmvdz** [comment]
Perhaps hooking into the application of fire aspect on the entity and adding an NBT compound entry on the entity could fix this?

**Comment by TheWinABagel** [comment]
That is very bizarre, will look into it

**Comment by TheWinABagel** [comment]
Hmm I can't recreate the issue with just KOTA and fire aspect in Prom 2 on the same sword, I'll check through the rest of the enchants to see if there might be some sort of other problem

**Comment by TheWinABagel** [comment]
Question, is it *never* proccing KOTA? or just sometimes? Because the Echo enchantment (and all other AOE damage enchantments from MCDW) appears to not pass the information needed to figure out if KOTA should proc

**Comment by TheWinABagel** [comment]
I couldn't find an issue with any of the other enchantments, this is quite odd

**Comment by lmvdz** [comment]
If the fire tick causes the kill the KOTA enchant doesn't proc, and items are dropped.

**Comment by TheWinABagel** [comment]
It looks like [this](https://modrinth.com/mod/hotshot) mod fixes the issue (as it is a vanilla issue)

**Comment by lmvdz** [comment]
Nice!
