### ISSUE TITLE
Client crash when opening inventory (Quilt, doesn't happen on Fabric)

### ISSUE THREAD

**Issue by TeslaP09** [TheWinABagel/Zenith#82]
Issue: The client instantly crashes instantly when opening the player's inventory. I originally had this issue in a huge modpack, but when I created a new test instance and installed only the neccesary mods, the issue persisted.

According to the crash report, the problem is this line right here 
https://github.com/TheWinABagel/Zenith/blob/9e9444d2c525409cfc87ca01540fbbe791ffafc9/src/main/java/dev/shadowsoffire/apotheosis/adventure/loot/RarityRegistry.java#L74C8-L74C8
I'm not a programmer, but the code seems to subtract 1 from a value that is already 0, so it results in a number lower than 0 which java appearantly doesn't like, because it throws an out of bounds error...

Weirdly though, the issue doesn't exist on fabric for some reason.

EDIT: The comment below the line seems to be describing this issue, so I don't know if I should leave the issue open, seeing that you already know about it. Feel free to close it if you do.

Mod loader: Quilt (0.22.4 beta, also tested with 0.22.0 release)

Mods installed: Fakerlib 0.0.9, Patchouli 83, Quilted Fabric API 7.4.0, Zenith Attributes 0.1.1, Zenith 0.2.4

Crash report:
[crash-2023-12-16_14.01.32-client.txt](https://github.com/TheWinABagel/Zenith/files/13692655/crash-2023-12-16_14.01.32-client.txt)

**Comment by sleepy-evelyn** [comment]
I get the same issue. Using QFAPI 7.4.0+0.90.0-1.20.1 and Quilt Loader 0.22.1-beta4.

I doubt it's a Quilt only issue but I know QFAPI 7.4.0+0.90.0 is far from being the latest version of the FAPI so maybe that's why. It's worth testing with older QFAPI versions maybe, namely 0.90.0.

**Comment by TheWinABagel** [comment]
Just tested with an in dev version, it seems to be working? Let me know if the next version fixes it (hopefully will be released in the next few days)

**Comment by TheWinABagel** [comment]
Seems to be fixed
