### ISSUE TITLE
[Bug] Bosses not spawning

### ISSUE THREAD

**Issue by beam1ng** [TheWinABagel/Zenith#83]
After generating a new world, only one boss spawns per dimension. Changing the "Boss Spawn Cooldown" in `adventure.config` file doesn't have any affect.

The bug seems to be present since the commit introducing Zenith 0.2.0: https://github.com/TheWinABagel/Zenith/commit/da189b9a5de2760bcf7951897f3e35c72d118e1e
The commit altered the `BossEvents.java` file which might be relevant to the issue. 

Tested on versions:
- 0.2.4 - Bug *is* present
 - 0.2.0 - Bug *is* present
 - 0.1.11 - Bug is *not* present
 - 0.1.5 - Bug is *not* present

**Comment by TheWinABagel** [comment]
I never registered the tick event to reduce the cooldown of the boss spawning... 
Fixed next version
