### ISSUE TITLE
[Bug/Update]? Salvaging table automation

### ISSUE THREAD

**Issue by AlienXtream** [TheWinABagel/Zenith#84]
cant seem to get itens into/out of the salvaging table. wondering if this is a bug or that the mod isn't porting based off the latest version of apotheosis.

**Comment by TheWinABagel** [comment]
I haven't implemented that yet, it uses a forge system (forge capabilities) that doesn't have a direct equivalent on fabric, so I'll have to rewrite some things for it

**Comment by AlienXtream** [comment]
ah. so technically a "bug" but one pending a fix. would it be possible for a datapack to add in a recipe elswhere as a workaround? or are datapacks more limited in how they do recipes in this context (i.e knowing about the affix tier and/or variable output quantities)?

**Comment by TheWinABagel** [comment]
Yeah, datapacks wouldn't work for that sadly (Apologies for the delay with the response, have been busy with the holidays 😞)

**Comment by TheWinABagel** [comment]
Added in 1.0.3
