### ISSUE TITLE
problem with mod

### ISSUE THREAD

**Issue by malberz** [TheWinABagel/Zenith#87]
I'm playing with the build "Better MC[Fabric] - BMC1" on the version of the build "Better Minecraft[Fabric]v12", I decided to install Zenit because I like apotheosis. When I improve my enchantment table, the level does not increase

![image](https://github.com/TheWinABagel/Zenith/assets/154888163/683890ba-8bae-495b-acca-96929cb47c49)

![image](https://github.com/TheWinABagel/Zenith/assets/154888163/f293294b-17f6-43fe-adf9-63e4fd9bb575)

I don't know why this is, but I assume it's due to a mod conflict. tell me how to fix it
mod version apotheosis-0.2.6

**Comment by TheWinABagel** [comment]
Maybe easy magic? That version of the mod is ancient and unsupported though, so if that isn't the issue I can't help you
