### ISSUE TITLE
quilt resource loading broken

### ISSUE THREAD

**Issue by annahla** [TheWinABagel/Zenith#9]
when using zenith on quilt, resource loading is broken in some way or another. either:

1. it'll load up fine, however RecipeHelper never gets reloaded, so nothing has recipes and `Registered n additional recipes.` never gets printed. can be reproduced with minecraft 1.19.2, quilt loader 0.18.9, zenith 0.5.5, and quilt standard library 4.0.0-beta.30.

2. it'll error on world load, unable to find anything with a max quanta, kicking you to the main menu with `Internal Exception: java.util.NoSuchElementException: No value present`. actual error is attached as [error.txt](https://github.com/TheWinABagel/Zenith/files/11238116/error.txt). can be reproduced as above, except with EMI 0.7.3 added.

of note is that which situation happens seems to depend on the modlist, rather than specific mods. reproduction across machines may be hard as quilt doesn't enforce a load order apart from how the local JRE internally orders a HashMap of the mods. presumably, load order fuckery?

when using fabric loader 0.14.19 and fabric api 0.76.0, with or without EMI 0.7.3, it works fine.

thanks!!

**Comment by TheWinABagel** [comment]
I don't currently have time nor knowledge to support quilt and fabric, especially if such an important part of the mod is broken, but once I have a bit more time I'll look into this. For now I'll keep this issue open though

**Comment by Shibva** [comment]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/38770780/235898362-9217d0f0-d6ce-48ba-956d-51c497d44af1.png">
I can confirm that issue 2 seems to be resolved however issue 1 is somewhat present; though the pull request once its updated and or looked though by hand should fully patch both problems this issue has

**Comment by Shibva** [comment]
I would like to note that replacing the current contents of the lattest Jar v0.5.7 wtih the cleaned up recipies in the merge that all recipes are working as intended and are respecting the configuration modules; though I would recomend going though it to 1, check if all the recipes are the same as in Apotheosis, and 2. organize any specific misc recipe into its proper folder if needed


Other than that it looks as if the merge is fine to me

**Comment by Shibva** [comment]
I stand corrected, issue 2 is still present

**Comment by Shibva** [comment]
Ok so I found issue 2 still seem to be present; however I seem to have found that issue 2 does not occur when I use quilt though a forge mod called jumpquilt
(a mod that "hijacks" the forge modloader thing and boots it using the latest version of quilt loader instead)

**Comment by Shibva** [comment]
@TheWinABagel @annahla 

UPDATE: I made a fork of the space and made merged the pull. After testing it in a pure quilt instance, issue 2 was inadvertently corrected. Whatever chages were made alongside the recipe fixes, it also fixed the "Internal Exception: java.util.NoSuchElementException: No value present" as well.


How it will act in a fabric environment is unknown however, it should be noted that QUILT is a fork of fabric and quilt does have backwards compatibility for Fabric mods because its a fork (please note that you will need to use the quilt API instead, mods that use the Fabric API will work wtih the quilt API)
