### ISSUE TITLE
Not technically a bug but driving me crazy. 

### ISSUE THREAD

**Issue by linaraincalzando** [TheWinABagel/Zenith#90]
When interacting with any of Zenith tables if I am holding piece of armor it equips it.

**Comment by TheWinABagel** [comment]
That does sound annoying, but I don't know exactly how to fix that... hmm
I'll look into it, but no promises on finding anything

**Comment by linaraincalzando** [comment]
After further play I can confirm its not just armor but anything that has a use. For example if I have a spectrum knowledge gem in the inventory slot that I am using interacting with zenith tables the interaction is also having you interact with the knowledge gem to causing it to give you the experience in the gem like a continuous right click. I hope that info helps.

**Comment by solonovamax** [comment]
> That does sound annoying, but I don't know exactly how to fix that... hmm
> I'll look into it, but no promises on finding anything

most likely what is happening is you're not cancelling the right click action before opening the screen

**Comment by linaraincalzando** [comment]
To clarify, I was just using the knowledge gem as an example of what it happening being not only an action but a persistent interact of the right click because it is in continuous use. The Spectrum knowledge gem only gives
 experience back when actively being right clicked with.

**Comment by TheWinABagel** [comment]
> > That does sound annoying, but I don't know exactly how to fix that... hmm
> > I'll look into it, but no promises on finding anything
> 
> most likely what is happening is you're not cancelling the right click action before opening the screen

Ah yeah that was it, was PASS instead of CONSUME
I feel really dumb now lol
Fixed in the next version
