### ISSUE TITLE
Cannot craft Deepshelf of Arcane Treasures

### ISSUE THREAD

**Issue by solonovamax** [TheWinABagel/Zenith#92]
The recipe json uses the tags `minecraft:gold_block` and `minecraft:emerald_block`, however these are not real tags.

The correct tags to use are `c:gold_blocks` and `c:emerald_blocks`, or just use the item directly.

See: https://github.com/TheWinABagel/Zenith/blob/1.20/src/main/resources/data/zenith/recipes/treasure_shelf.json#L14-L25

![image](https://github.com/TheWinABagel/Zenith/assets/46940694/5b1e0348-ee25-4daa-8d23-b5689a5052c1)
![image](https://github.com/TheWinABagel/Zenith/assets/46940694/5fcd421b-5d0e-4f61-be77-00a92308f0f1)

**Comment by TheWinABagel** [comment]
Fixed with 1.0.1
