### ISSUE TITLE
Mod Incompatibility:Easy Anvils

### ISSUE THREAD

**Issue by Cynical1115** [TheWinABagel/Zenith#94]
Zenith version:1.0.1-1.20.1
EasyAnvils version:v8.0.1-1.20.1-Fabric

When the Easy Anvils mod is installed with Zenith,the vast majority of Easy Anvil's features will become invalid(such as editing name tags without cost).
So can Zenith's modifications to the anvil be a configurable option? Or maybe it does exist, but I haven't found it yet.

**Comment by TheWinABagel** [comment]
Easy Anvil support is not currently planned.
