### ISSUE TITLE
Chronicle of Shadows not working

### ISSUE THREAD

**Issue by vortxxswirly** [TheWinABagel/Zenith#99]
If i collect an item, the book disappears and the collected item takes its place. when i go into creative to grab the book, it doesn't open. I'm using 0.7.1+1.19.2 on a server using Fabric 0.15.5.

**Comment by TheWinABagel** [comment]
Do you have patchouli installed?

**Comment by TheWinABagel** [comment]
Presumed issue with no Patchouli
